version: '3.8'

services:
  # ArangoDB Database (Community Edition - Free)
  arangodb:
    image: arangodb:latest
    container_name: blacksmith-atlas-db
    environment:
      - ARANGO_ROOT_PASSWORD=atlas_password
      - ARANGO_DB_NAME=blacksmith_atlas
    ports:
      - "8529:8529"
    volumes:
      - ./data/arango_data:/var/lib/arangodb3
      - ./data/arango_apps:/var/lib/arangodb3-apps
    networks:
      - atlas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache (for performance optimization)
  redis:
    image: redis:7-alpine
    container_name: blacksmith-atlas-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - atlas-network
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blacksmith-atlas-backend
    ports:
      - "8000:8000"
    environment:
      - ATLAS_ENV=${ATLAS_ENV:-development}
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=${ARANGO_PORT:-8529}
      - ARANGO_USER=${ARANGO_USER:-root}
      - ARANGO_PASSWORD=${ARANGO_PASSWORD:-atlas_password}
      - ARANGO_DATABASE=${ARANGO_DATABASE:-blacksmith_atlas}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-default-secret-key}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      - ${ASSET_LIBRARY_PATH:-/net/library/atlaslib}:/app/assets
      - ${LOG_PATH:-./logs}:/app/logs
    depends_on:
      - arangodb
      - redis
    networks:
      - atlas-network
    restart: unless-stopped

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blacksmith-atlas-frontend
    ports:
      - "3011:3011"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - atlas-network
    restart: unless-stopped

# volumes:
  # arango_data:
  # arango_apps:
  # redis_data:

networks:
  atlas-network:
    driver: bridge 