version: '3.8'

services:
  # Backend API (Production - connects to external ArangoDB)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blacksmith-atlas-backend
    ports:
      - "8000:8000"
    environment:
      - ATLAS_ENV=${ATLAS_ENV:-production}
      - ARANGO_HOST=${ARANGO_HOST}
      - ARANGO_PORT=${ARANGO_PORT:-8529}
      - ARANGO_USER=${ARANGO_USER}
      - ARANGO_PASSWORD=${ARANGO_PASSWORD}
      - ARANGO_DATABASE=${ARANGO_DATABASE:-blacksmith_atlas}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - COMFYUI_HOST=${COMFYUI_HOST:-localhost}
      - COMFYUI_PORT=${COMFYUI_PORT:-8188}
    volumes:
      - ${ASSET_LIBRARY_PATH:-./assets}:/app/assets
      - ${LOG_PATH:-./logs}:/app/logs
    networks:
      - atlas-network
    restart: unless-stopped

  # Frontend (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blacksmith-atlas-frontend
    ports:
      - "3011:3011"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - atlas-network
    restart: unless-stopped

networks:
  atlas-network:
    driver: bridge